### ISSUE TITLE
List of linkshells and characters

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#12]
Josh, does you XIVDB have a list of linkshells and characters? When updating FFTracker tomorrow or the day after, I'd like to grab as much as possible and since XIVDB already tracks a lot of stuff, maybe you could share list of ids?
Thank you

**Comment by viion** [comment]
I dont do anything with Linkshell data right now.

**Comment by Simbiat** [comment]
I thought you may have Linkshell IDs. Well, if you don't, will think of something else then.
