### ISSUE TITLE
When the game is down for maintenance, the world status page can "break"

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#15]
Instead of listing the worlds and their statuses, you will get a page just saying:

> "The Server Status page cannot be updated due to system maintenance. View maintenance details."

This is a `200` response.

**HTML**
```html
<div class="ldst__window">
	<p class="parts__text parts__space--pt16">
			The Server Status page cannot be updated due to system maintenance. View maintenance <a href="http://eu.finalfantasyxiv.com/lodestone/news/category/2">details</a>.
	</p>
</div>
```

The current attempt will cause `500` PHP error when trying to retrieve the world status.

**Comment by viion** [comment]
@shentschel Any opinion on this? The page will be down whenever the servers go down but still returns 200.

I was thinking of checking for the html tag `p.parts__text.parts__space--pt16` as this doesn't exist when the page renders as normal.

**Comment by shentschel** [comment]
I would do the same as I don't know if there is another way to check it.

**Comment by viion** [comment]
Fixed via: https://github.com/viion/lodestone-php/issues/45
