### ISSUE TITLE
integrate api into a ci environment

### ISSUE THREAD

**Issue by shentschel** [viion/lodestone-php#18]
When #7 is done we should think about adding the api to a travis, jenkins, `insert your favorite CI environment here` node. This would keep track if we break stuff while developing :)

**Comment by viion** [comment]
I have no knowledge of these services but it would be super cool. (are they free?)

**Comment by shentschel** [comment]
I can provide the knowledge. Jenkins in itself is open source so we could use it. All we need is a server with java to start it.

https://travis-ci.com/plans seems to be free for open source projects. I think we can test and decide that when #7 and #19 are done x)

**Comment by viion** [comment]
Travis-CI has been added to the repo. It will run the tests on `master` and `dev`. Decided not to run them on all PR's because tests requiring queuing Lodestone and can take some time to complete...

https://travis-ci.org/viion/lodestone-php/branches
