### ISSUE TITLE
Seperate unit tests from integration tests

### ISSUE THREAD

**Issue by shentschel** [viion/lodestone-php#19]
After #7 is done and before #18 we should seperate unit tests from integration tests.

The reason for this is, that we want to test every module on its own if it works like we want. (Unit test)
But we also want that the api can work with live data (integration test). For that we should implement an end-to-end test where we can check if the api produces the expected results for a given query.

**Comment by shentschel** [comment]
Quick thoughts for that topic:

* A unit test only tests a single unit of the whole process 
  * We should provide static fixtures for testing a unit
    * Fixtures for good cases where a unit is working like expected
   * Fixtures for bad stuff like #66 to see how a unit is reacting
* A integration test should actually pull data from the lodestone
  * It tests if the whole process is working with real data
  * If a tests fail without any change, then we know that SE changed something on the lodestone

The main difference between both tests is that we can expect an outcome out of a unit (we wrote it with a specific behavior in mind). The tests ensures that we know that we broke something when we change some stuff. In an integration test we see if the integration of all units work like we expect. For that case the integration tests should be done with real data so that we can also track that the data from lodestone are the same as we expect.

Some opionions, thoughts, etc.? I welcome feedback :)

**Comment by viion** [comment]
Can do both tests, I've no problem with that. I've just be doing integration tests against characters as they're more important right now.

**Comment by viion** [comment]
This is quite old but as I've been doing a ton of testing in my main job, some ideas to improve things

- https://github.com/viion/lodestone-php/blob/master/tests/Lodestone/Entities/CharacterTest.php these should be e2e tests, not Unit tests
- https://github.com/viion/lodestone-php/blob/master/tests/Lodestone/Validator/BaseValidatorTest.php these are good, however data sets would be cleaner
- Implement mocking for http requests and return various html samples for the parser
- Make the benchmark script more "professional", needs cleaning up (this would be a sort of load test setup): https://github.com/viion/lodestone-php/blob/master/tests/bench.php
- Move to e2e: https://github.com/viion/lodestone-php/blob/master/tests/run.php

**Comment by viion** [comment]
Closing this as the repository is going to be discontinued.
