### ISSUE TITLE
Free Company members pagination

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#2]
There seems to be no pagination for FC mbembers. This is how I worked around this, actually retrieving the whole list of characters:
in Routes.php updated routes:
```php
    const LODESTONE_FREECOMPANY_MEMBERS_URL = self::LODESTONE_URL .'lodestone/freecompany/%s/member/?page=1';
    const LODESTONE_FREECOMPANY_MEMBERS_PAGE_URL = self::LODESTONE_URL .'lodestone/freecompany/%s/member/?page=%s';
```
Original one was updated for consistency, rather than anything else

in FreeCompanyMembers.php updated pageCount() to get FCID if possible (will be present in case of multiple pages:
```php
    /**
     * Parse page count
     */
	private function pageCount()
	{
		// page count
		$data = $this->getDocument()->find('.btn__pager__current', 0)->plaintext;
		list($current, $total) = explode(' of ', $data);
		if ($fchref = $this->getDocument()->find('ul.btn__pager:nth-child(4) > li:nth-child(4) > a:nth-child(1)', 0)->href) {
			$fcid = explode('/', $fchref);
			if (count($fcid) >= 6) {
				$this->add('fcid', $fcid[5]);
			}
		}
        $current = filter_var($current, FILTER_SANITIZE_NUMBER_INT);
        $total = filter_var($total, FILTER_SANITIZE_NUMBER_INT);

		$this->add('page_total', $total);
		$this->add('page_current', $current);

		// member count
        $data = $this->getDocument()->find('.parts__total', 0)->plaintext;
        $data = filter_var($data, FILTER_SANITIZE_NUMBER_INT);
        $this->add('character_total', $data);
	}
```

And "recursed" parseList():
```php
    /**
     * Parse members
     */
	private function parseList()
	{
		$rows = $this->getDocumentFromClassname('.ldst__window');

		$characters = [];
		foreach($rows->find('li.entry') as $node) {
			$characters[] = [
			    'id' => explode('/', $node->find('a', 0)->getAttribute('href'))[3],
			    'name' => trim($node->find('.entry__name')->plaintext),
                'server' => trim($node->find('.entry__world')->plaintext),
                'rank' => trim($node->find('.entry__freecompany__info span', 0)->plaintext),
                'avatar' => explode('?', $node->find('.entry__chara__face img', 0)->src)[0],
            ];
		}

		$this->add('members', $characters);
		if ($this->data['page_total'] > 1 && $this->data['page_current'] != $this->data['page_total'])
		{
			$pageparser = new FreeCompanyMembers();
			$pagedata = $pageparser->url(sprintf(\Lodestone\Modules\Routes::LODESTONE_FREECOMPANY_MEMBERS_PAGE_URL, $this->data['fcid'], $this->data['page_current'] + 1))->parse();
			$this->data['members'] = array_merge($this->data['members'], $pagedata['members']);
		}
	}
```
Probably, the same can be done for linkshells, as well, but did not check, since am not tracking at the moment.

**Comment by viion** [comment]
Paging can be done by just adding the query onto the end. I have a test controller and this is my code:

```php
$params = [];

// page is optional
if ($page = $request->get('page')) {
    $params[] = sprintf('page=%s', intval($page));
}

// build request
$params = $params ? '?' . implode('&', $params) : '';
$url = sprintf(LODESTONE_FREECOMPANY_MEMBERS_URL, $id) . $params;
$parser = new \Sync\App\FreeCompanyMembers();
$data = $parser->requestFromLodestone($url);
```

This run's on silex and I use a custom App in Sync because I have database operations. The key bit is

```php
$params = $params ? '?' . implode('&', $params) : '';
$url = sprintf(LODESTONE_FREECOMPANY_MEMBERS_URL, $id) . $params;
```

I don't think something like this should really be baked into the routes, I am planning to put out a wrapper around the parsing so you don't need to provide routes, so there would be a function like this:

```php
$page = 5;
$api = new Lodestone\Api();
$api->getFreeCompanyMembers($id, $page);
```

I am not sure if recurrsive fetching should be part of the library yet or external features, because what I would do is something like:

```php
$pageparser = new FreeCompanyMembers();
$url = sprintf(\Lodestone\Modules\Routes::LODESTONE_FREECOMPANY_MEMBERS_URL, xxx);
$parser = new Lodestone\Parser\FreeCompanyMembers();
$data = (Object)$parser->url($url)->parse();

if ($data->page_total > 1) {
   $page = 2;
   while($page <= $data->page_total) {
     $moreData = (Object)$parser->url($url .'?page=' $page)->parse();
     $data->members = array_merge($data->members, $moreData->members);
     $page++;
   }
}
```

This way the loop is part of you control, it isn't reinitializing the `FreeCompanyMembers` (In PHP creating a class is memory hungry) and you're just adding onto the existing data object.

**Comment by Simbiat** [comment]
Well, obviously there are more ways to do that (= My idea was to point it out, that we are not getting the whole list of characters and shared my head-on approach :D 
I also added
```php
'rankicon' => trim($node->find('.entry__freecompany__info img', 0)->src),
```
Old Lodestone showed had rank ID, now it does not, and I need that. Will be array-replacing image names, I guess.

**Comment by viion** [comment]
Added in rank icon!

**Comment by viion** [comment]
I wonder if an option could be provided to do this built in. My worry is if someone pares a FC with 500 members and is waiting for 10 pages to download and it become's unstable.

So you'd do

```php
$data = (Object)$parser->url($url)->pagination()->parse();
```

Thoughts?

**Comment by Simbiat** [comment]
option, could be a good thing, like send an extra "true" to parse all pages recursively. as for time, I do not think there is any actual service parsing free companies right now besides mine and I do output info on the update progress either way... With whole FC update for big companies stretching up to several minutes... And I still do it 2 times a day only. So, should not be much of an issue in that regard (=

**Comment by viion** [comment]
I've added an API class which now covers this issue: https://github.com/viion/lodestone-php/blob/master/src/Lodestone/Api.php

```php
$api = new \Lodestone\Api();

// search on page 4
$api-> searchCharacter('Name', 'Server', 4)
```
