### ISSUE TITLE
Implement multi-language support

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#20]
Right now the parser only supports English(`na` domain).

Would like to support more languages, this would also include fetching multi-language data from XIVDB and provide errors in the users chosen language.

- French: fr.finalfantasyxiv.com/lodestone/character/730968/
- German: http://de.finalfantasyxiv.com/lodestone/character/730968/
- Japanese: http://jp.finalfantasyxiv.com/lodestone/character/730968/

**Comment by shentschel** [comment]
hmm if we want to provide multi language support. Maybe we should dig into i18n. This would allow us to separate all error- or info-messages from the code and we don't need to change the code when a new language will be introduced.

**Comment by viion** [comment]
Could do, however I think i18n might be overkill. We would only have a very few error messages that are specific to lodestone (others can stay English)

Parsing lodestone multi-language also needs doing which is a bit separate.

**Comment by Simbiat** [comment]
I have some ideas on how to implement this more or less transparently. Will try to work on this.

**Comment by Simbiat** [comment]
#92 was updated with ability to change UserAgent and set language for LodeStone. Changing language breaks some of the parsers at the moment, though, but I will update it accordingly. Implementation is a bit dirty, but it's a start, for sure.

**Comment by viion** [comment]
Closing this as the repository is going to be discontinued.
