### ISSUE TITLE
Add validation and Tests for stats

### ISSUE THREAD

**Issue by shentschel** [viion/lodestone-php#21]
In addition to #14:

We should add a validation for stats.

and as note for the future: we need to add an integration test which ensures that we get stats from SE :)

**Comment by viion** [comment]
What do you propose? Just loop through them and check there is a name/value?

We can't use a Struct since depending on if you're in PVP or Gathering or Crafting, you get different stats.

**Comment by shentschel** [comment]
yeah that's what I would do for now.

Something like:

```php
$validator = new CharacterValidator();

foreach($box->find('.character__param__list', 3)->find('tr') as $node) {
  $name = $node->find('th')->plaintext;
  $validator
    ->check($name, 'Name')->isString()
    ->validate();

  $id = $this->xivdb->getBaseParamId($name);
  $validator
    ->check($id, 'ID')->isId()
    ->validate();

  $value = intval($node->find('td')->plaintext);
  $validator
    ->check($value, 'Value')->isInteger()
    ->validate();

  $stats['physical'][$name] = [
    'id' => $id,
    'name' => $name,
    'value' => $value
  ];
}```

The reason why I have 3 validations instead of one is to fail fast. DOM operations with xpath are very expensive in terms of memory and cpu x)

**Comment by viion** [comment]
I was thinking of moving validation into the parses themselves rather than separate. It does mean assigning all variables before appending to array..

**Comment by viion** [comment]
Propose removing my blueprint: https://github.com/viion/lodestone-php/blob/master/src/Lodestone/Parser/Character.php#L141

Putting validation inside the parses.

Maybe parsing could be broken up more... Some of the functions are getting very lengthy.

**Comment by shentschel** [comment]
Putting them inside the parses sounds cool. Maybe we can do a refactoring of the parses to decrease their length :) I'll have a look into it. Maybe I can come up with a nice idea :)

**Comment by viion** [comment]
I did a **ton** of parse testing, if you can refactor it down a bit more that would be good so long as it maintains it's speed (i was working with 1000ths of a second speed increases) 

If you enable `printtime` you can check. I did do some testing of adding a validation check within the parse vs done after, there was no difference in time as the same resources are used and validation is extremely light anyway.

**Comment by shentschel** [comment]
I will have a look into that :) thanks for the tip. Maybe we can also automate the the performance tests in the near future.

**Comment by shentschel** [comment]
I have a proposal which I want to discuss :)

for the proposal I'll borrow a few lines of code from the parsing of the profile:

```php
// get mounts
$mounts = [];
Logger::printtime(__FUNCTION__.'#'.__LINE__);
foreach($box->find('.character__mounts ul li') as $node) {
  // name
  $name = trim($node->find('.character__item_icon', 0)->getAttribute('data-tooltip'));
  $id = $this->xivdb->getMountId($name);
  $icon = $this->xivdb->getMountIcon($id);
  $mounts[] = [
    'id' => $id,
    'name' => $name,
    'icon' => $icon,
  ];
}
$this->add('mounts', $mounts);

// get minions
$minions = [];
Logger::printtime(__FUNCTION__.'#'.__LINE__);
foreach($box->find('.character__minion ul li') as $node) {
  // name
  $name = trim($node->find('.character__item_icon', 0)->getAttribute('data-tooltip'));
  $id = $this->xivdb->getMinionId($name);
  $icon = $this->xivdb->getMinionIcon($id);
  $minions[] = [
    'id' => $id,
    'name' => $name,
    'icon' => $icon,
  ];
}
```
I did a little test how fast the creation of a small array with the entries 'id', 'name' and 'icon' is.
To have a comparable value I created a mini entity class which looks like:

```php

public class Minion {
  public $id;
  public $name;
  public $icon;

  public function __construct($id, $name, $icon) {
    $this->id = $id;
    $this->name = $name;
    $this->icon = $icon;
  }
}
```
For the test I created the following code:

```php
include_once 'Minion.php';

echo "Output 10.000 Minions (object)";
echo '<br />';
$arr = [];
$start = microtime(true);
for($i = 0; $i < 10000; $i++) {
    $arr[] = new Minion($i, sprintf('Name %d', $i), $i);
}
$end = microtime(true);
unset($arr);
echo 'Needed Time: ' . ($end - $start);

echo '<br />';
echo '<br />';

echo 'Output 10.000 Minions (array)';
echo '<br />';
$start = microtime(true);
$arr = [];
for($i = 0; $i < 100000; $i++) {
    $arr[] = [
        'id' => $i,
        'name' => sprintf('Name %d', $i),
        'icon' => $i
    ];
}
$end = microtime(true);

echo 'Needed Time: ' . ($end - $start);
```

The result was:

```
Output 10.000 Minions (object)
Needed Time: 0.0018830299377441

Output 10.000 Minions (array)
Needed Time: 0.013065099716187
```

So my proposal would be to create an entity model of all data which will be decoupled from the current parsing stuff.
In the entity we could then add the validation (Example not tested):

```php
public class Minion {
  public $id;
  public $name;
  public $icon;

  public function __construct($id, $name, $icon) {
    $validator = new BaseValidator();
    $validator
      ->check($id, 'ID')
      ->isInteger()
      ->validate();
    $this->id = $id;
      
    $validator
      ->check($name, 'Name')
      ->isNotEmpty()
      ->isString()
      ->validate();
    $this->name = $name;

    $validator
      ->check($icon, 'Icon URL')
      ->isNotEmpty()
      ->isString()
      ->validate();
    $this->icon = $icon;
  }
}
```
IMHO that would solve the size of the parser structure and it would also fail fast enough to see if something is buggy with one of the data entries.

@viion How do you think about that? :)

**Comment by viion** [comment]
This is really cool, I was reading up about Arrays vs Objects (even `stdClass`) since PHP is an unfixed array size it's basically a hash map, which is slooooow. However objects you define the params and it knows it can make an list of `x` params, fixed length. Thus super fast.

Plus it would provide very nice features where we provide a class back instead of an array (can always add an `toArray` method.

**Comment by shentschel** [comment]
yeah there is also the possibility to implement JsonSerializable :) That would allow us to define which variables are exposed via json_encode

**Comment by shentschel** [comment]
This will be a really big change for the api.
I think I will split it up in multiple PR so that we can discuss them a little better :)
I will begin with the Profile Parsing I think I can finish that tomorrow :)

**Comment by viion** [comment]
Much of the logic behind this is complete and decided through the code done by @shentschel.

Validator classes are to be built for the different entities (Character, Achievements, Free Company, Linkshell). These validators contain any unique validation for themselves and extend the `BaseValidator` which has generic validation checks.

Validation checks should be done when populating an object. Example of usage:

```php
// Lodestone\Entities\Character\GrandCompany

public function setIcon(string $icon)
{
    $this->validator
        ->check($icon, 'Icon URL')
        ->isInitialized()
        ->isNotEmpty()
        ->isString()
        ->validate();
    
    $this->icon = $icon;

    return $this;
}
```

**Comment by viion** [comment]
Marking this complete as it's based on validation and specifically stats, which is now complete and a format has been established. Future issues could be the lack of validation in specific areas.

Format and example of stats: https://github.com/viion/lodestone-php/blob/dev/src/Lodestone/Entities/Character/Attribute.php
