### ISSUE TITLE
Refactor Id parsing

### ISSUE THREAD

**Issue by shentschel** [viion/lodestone-php#27]
Currently we are parsing the id even when we provide it before.

So we should use the provided id because parsing html costs a hugh amount of time!

**Comment by viion** [comment]
The idea for this is complete, It will be provided as a mandatory requirement to the Parser:

```php
$url = '...';
$id = '12345';

(new CharacterParser($id))->url($url)->parse();
```

In the construct for the CharacterParser, it is provided to the top level object:

```php
$this->profile = new Profile($id);
```

This logic would be the same for all entities:
- Achievements
- Free Company
- Linkshell

**Comment by viion** [comment]
Todo:

- [ ] Achievements (unsure if it's needed)
- [ ] Free Company
- [ ] Linkshell
