### ISSUE TITLE
Fatal Error on missing character

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#3]
Seems like, if we try to search for a character, that was removed (for example 16412004), we get a set of warning that end in fatal error:

> PHP Warning:  dom_import_simplexml() expects parameter 1 to be object, boolean given in root\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/company/9234631035923213559/
> PHP Notice:  Trying to get property of non-object in root\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/company/9234631035923213559/
> PHP Notice:  Trying to get property of non-object in root\\Lodestone\\Dom\\Document.php on line 197, referer: http://192.168.1.5/fftracker/company/9234631035923213559/
> PHP Notice:  Trying to get property of non-object in root\\Lodestone\\Dom\\Document.php on line 197, referer: http://192.168.1.5/fftracker/company/9234631035923213559/
> PHP Warning:  Invalid argument supplied for foreach() in root\\Lodestone\\Dom\\Document.php on line 197, referer: http://192.168.1.5/fftracker/company/9234631035923213559/
> PHP Warning:  dom_import_simplexml() expects parameter 1 to be object, boolean given in root\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/company/9234631035923213559/
> PHP Notice:  Trying to get property of non-object in root\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/fftracker/company/9234631035923213559/
> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to DOMXPath::__construct() must be an instance of DOMDocument, null given in root\\Lodestone\\Dom\\Document.php:156\nStack trace:\n#0 root\\Lodestone\\Dom\\Document.php(156): DOMXPath->__construct(NULL)\n#1 root\\Lodestone\\Parser\\Character.php(56): Lodestone\\Dom\\Document->find('.frame__chara__...', 0)\n#2 root\\Lodestone\\Parser\\Character.php(34): Lodestone\\Parser\\Character->parseProfile()\n#3 root\\fft-functions.php(450): Lodestone\\Parser\\Character->parse()\n#4 root\\fft-functions.php(594): lodestone_grab('16412004', in root\\Lodestone\\Dom\\Document.php on line 156, referer: http://192.168.1.5/fftracker/company/9234631035923213559/

**Comment by Simbiat** [comment]
Working on fix (will update as I go):
Document.php:
replace
```php
$this->document = dom_import_simplexml($sxe)->ownerDocument;
```
with
```php
        	if ($sxe !== false) {
           		$this->document = dom_import_simplexml($sxe)->ownerDocument;
        	} else {
        		return false;
        	}
```

**Comment by Simbiat** [comment]
Now... for the rest it seems like even though original code could return null
```php
	        return (isset($elements[$idx])) ? $elements[$idx] : null;
```
it's not handled anywhere...

**Comment by Simbiat** [comment]
For some reason, is404 was not firing properly, thus we got
> Call to a member function getAttribute() on null
I added workaround in my previous comment. now it seems fine

**Comment by viion** [comment]
I don't seem to get this error

```
http://xiv.sync/character/parse/16412004
https://xivsync.com/character/parse/16412004
{
    "success": true,
    "data": false
}
```

**Comment by viion** [comment]
Found the issue, I handle false statements independent so I can catch this kind of thing because I handle http statuses, found here: https://github.com/viion/lodestone-php/blob/master/src/Lodestone/Modules/HttpRequest.php#L52

So when it tries to do: `is404` the `$html` variable is false and thus returns `-1`.

**Comment by Simbiat** [comment]
yes. seems like just updating is404 like I mentioned is enough

**Comment by Simbiat** [comment]
Tested your update and it works, as well. Closing the issue, then.

**Comment by Simbiat** [comment]
Actually, I just encountered the same with Free Company - 923702357322532. And restoring is404 to the way I suggested before worked around it as expected. Moving around
```php
$html = $this->trim($html, 'class="ldst__main"', 'class="ldst__side"');
```
which you did with Character did not have results for me. I guess same thing can happen with likshells, too

**Comment by viion** [comment]
Pushed a fix if you want to test

![](http://i.imgur.com/OpyvLc7.png)

**Comment by Simbiat** [comment]
Strange, when I did the same on my side it did not work, but now it did... Mystery :D
