### ISSUE TITLE
Create a markdown document explaining: Benchmark/Development

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#32]
Create a markdown document that explains how the Benchmark is used, what it's purpose is and how it can be used to aid in development of the API.

**Comment by shentschel** [comment]
Proposal:

In a future work we should merge the benchmark feature into the testsuite.
So we can have tests which are failing the parsing takes longer than a prespecified max time.

**Comment by viion** [comment]
I've added a doc that explains the benchmark tool for development, got anything to add?

https://github.com/viion/lodestone-php/blob/98d03195719a81ea9833af183bc5d00e368e5e35/docs/DevBenchmarking.md

Otherwise going to merge this. I see your point about putting it into testsuite but that should be a separate task (if you want to create one). It might be difficult to test it as it wholly depends on peoples machines. A Linode CPU is going to process things a ton faster than someones local dev so we would need to be quite relax'd on time limits.

**Comment by shentschel** [comment]
yeah that would be a problem with different machines.

BTW: in the docs at chapter [Timing foreach loops][1] you say that there are 3 parameters but the function only contains 2 or did I misread something? x)

[1]:https://github.com/viion/lodestone-php/blob/docs/docs/DevBenchmarking.md#timing-foreach-loops

**Comment by viion** [comment]
Updated :)
