### ISSUE TITLE
Introduce contribution guidelines

### ISSUE THREAD

**Issue by shentschel** [viion/lodestone-php#36]
This is only a proposal and open for discussions :)

IMHO we should provide a guideline how to contribute to the project. This should contain the following informations:

* Coding Style - A common scheme allows a new person to get easy onboard
* Commit Message Convention - This allows to have a more consistent history log
* Issue- and Branchingstrategies - allowing people to see how we work with issues and branches (and minimizing lost discussions in PRs

I'll provide an initial document in a PR for discussion in this issue :)

**Comment by viion** [comment]
You've written these, so they can be expanded and it's all good,

Related: https://github.com/viion/lodestone-php/issues/60
