### ISSUE TITLE
Time for DevPosts is incorrect

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#41]
My attempt at parsing dev posts time is coming out incorrect, a user has suggested this works for them:

```php
$forum_date = $post->find('.posthead .date', 0)->text();
// remove invisible characters
$forum_date = preg_replace('/[[:^print:]]/', ' ', $forum_date);

$date = new DateTime($forum_date, new DateTimeZone('Asia/Tokyo'));
$timestamp = $date->format('U');

$date->setTimezone(new DateTimeZone('Europe/Paris'));
$data['time'] = $date->format('Y-m-d H:i:s');
```

**Comment by shentschel** [comment]
I would have done the same. Is there something which discourages the use of that example?

**Comment by viion** [comment]
I don't think so, the main factors to keep in mind is forum dates are not consistent, and will say "Today" and "Yesterday", even if "Today" for the server is "Tomorrow" for the forums. However, the above code seems to work. Haven't tested.

**Comment by shentschel** [comment]
I would say, lets try it :) For the forum post.. we could create mock data which contains the words `Yesterday` or `Today` if needed :)

**Comment by viion** [comment]
This should be fixed now!
