### ISSUE TITLE
Missing Guardian and GrandCompany

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#44]
Guardian and GrandCOmpany information is missing for characters in latest release. Need to restore them

**Comment by viion** [comment]
Should be good now!

**Comment by Simbiat** [comment]
will have to wait till maintenance is completed

**Comment by Simbiat** [comment]
Solved

**Comment by Simbiat** [comment]
Seems like if there is no grandcompany I get this warning:
Undefined offset: 1 in root\\backend\\Lodestone\\Parser\\Character\\TraitProfile.php on line 192

**Comment by Simbiat** [comment]
Fixed in #53
