### ISSUE TITLE
SE changed copyright

### ISSUE THREAD

**Issue by shentschel** [viion/lodestone-php#48]
![image](https://user-images.githubusercontent.com/2470308/27191268-972b66fe-51f7-11e7-8360-f23d922072c3.png)

does that concern us?

**Comment by viion** [comment]
Not for the lodestone parser no, it concerns XIVDB which I put a statement out regarding.

**Comment by Simbiat** [comment]
Not sure if it affects me. I mean, I do provide leveling tracking, company ranks tracking... not sure, but I think that is considered data mining. or not?
