### ISSUE TITLE
Lodestone update -- Jun. 16, 2017 9:00 (GMT)

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#49]
Classes panel has changed, parse could be broken. Attributes changed slightly.

**Comment by viion** [comment]
They've changed roles to show Jobs and not classes

```
paladin": {
                "name": "Paladin",
                "level": 50,
                "exp": {
                    "current": 479419,
                    "max": 864000
              
```

**Comment by viion** [comment]
Because of job change i had to do this for sync on roles:

```
$classjobs = $this->data['classjobs'];

		$found = false;
		foreach($classjobs as $cj) {
			if (strtolower($cj['name_en']) == strtolower($name)) {
				$found = $cj;
				break;
			}
		}

		if ($found['is_job'] == 1) {
		    $found = $classjobs[$found['classjob_parent']];
        }

		return $found['id'];
```

i will need to apply to this later

**Comment by Simbiat** [comment]
is my understanding, that data.php also needs to be updated manually? or it can be updated automatically somehow? Character parser fails due to new classes

**Comment by viion** [comment]
Delete it and it should re-download.

**Comment by Simbiat** [comment]
There is a small problem, which was not easy to catch: your code seems to fail to validate SSL certificate and thus fails to get the API data. It's not obvious at all, but I was getting fatal errors on trying to redownload it and came down to updating code to use
```php
$json = file_get_contents(self::HOST . $route);
```
It then showed SSL errors. I replaced the API host to http, instead of https and it worked normally with original code as well.

**Comment by viion** [comment]
Thats odd, I don't get that issue, however using `http` is fine!

**Comment by Simbiat** [comment]
Also, even after update I keep getting:
```
PHP Notice:  Undefined index: 39762c71 in root\\backend\\Lodestone\\Modules\\XIVDBDataTrait.php on line 193
```
And I notice, that some classes show something like this:
```
      'id' => 22,
      'name' => 'Dragoon',
      'level' => 60,
      'expLevel' => 167400,
      'expLevelTogo' => 4302600,
      'expLevelMax' => 4470000,
      'expTotal' => 29638200,
      'expTotalMax' => 29470800,
      'expTotalTogo' => -167400,
```

as for http(s), perhaps I am missing some library? but I'd expect to get some kind of an error then... Dunno.

**Comment by viion** [comment]
That shouldn't happen once the xivdb file is updated?

**Comment by Simbiat** [comment]
Should not, but 39762c71 is not in data.php on my side

**Comment by viion** [comment]
Did you add in my modified fixed? i've not pushed it into the code

**Comment by Simbiat** [comment]
no. I only changed host address in current build

**Comment by viion** [comment]
I dont use this version live so I'll have to look later, however the code i posted needs adding to the gear role id fetch in xivdb class

**Comment by Simbiat** [comment]
no. I only changed host address in current build.

As for your code, do you mean, that it should be added to parseActiveClass()?

**Comment by Simbiat** [comment]
For some reason validator thinks, that http://eu.finalfantasyxiv.com/lodestone/character/14707825/ has wrong name. Seems like it does not like the apostrophe and... Funny thing, but seems like I can't even str_replace it.

**Comment by viion** [comment]
Very odd, would need to make a change to the regex, could you make a new issue with that profile?

As for active class

```
	// get the role id from a name
	public function getRoleId($name)
	{
		$classjobs = $this->data['classjobs'];

		$found = false;
		foreach($classjobs as $cj) {
			if (strtolower($cj['name_en']) == strtolower($name)) {
				$found = $cj;
				break;
			}
		}

		if ($found['is_job'] == 1) {
		    $found = $classjobs[$found['classjob_parent']];
        }

		return $found['id'];
	}
```

thats my old code, i might just do a simple array of `"Paladin" => "Gladiator"`

That way it doesn't rely on xivdb.

**Comment by Simbiat** [comment]
getRoleId is mentioned only in Lodestone.php and is actually being called, not declared.

**Comment by Simbiat** [comment]
Another undefined index with new data.php - 6fb9b226

**Comment by Simbiat** [comment]
39762c71 can't be found, because on LodeStone it means "Critical Hit Rate", but on http://api.xivdb.com/data/baseparams it's just "Critical Hit"

**Comment by viion** [comment]
SE do this a lot, it will have to be modified similar to elemental resistances. Could you create a new issue with it. 

What was the issue with `6fb9b226` ?

**Comment by Simbiat** [comment]
No idea. Created #52

**Comment by viion** [comment]
I have fixed class/job ids and update `xivdb.php`. I maintain the original name for the classjob (eg: Warrior or Paladin) but the correct ID should always return which it does now, eg:

```
[1] => Lodestone\Entities\Character\ClassJob Object
(
    [id:protected] => 1
    [name:protected] => Paladin
    [level:protected] => 50
    [expLevel:protected] => 479419
    [expLevelTogo:protected] => 384581
    [expLevelMax:protected] => 864000
    [expTotal:protected] => 8213419
    [expTotalMax:protected] => 29470800
    [expTotalTogo:protected] => 21257381
)
```

**Comment by viion** [comment]
Fixed max EXP

```
[activeClassJob:protected] => Lodestone\Entities\Character\ClassJob Object
(
    [id:protected] => 34
    [name:protected] => Samurai
    [level:protected] => 70
    [expLevel:protected] => 0
    [expLevelTogo:protected] => 0
    [expLevelMax:protected] => 0
    [expTotal:protected] => 100013800
    [expTotalMax:protected] => 100013800
    [expTotalTogo:protected] => 0
)
```

**Comment by viion** [comment]
I've fixed "Critical Hit Rate" getting wrong ID in the same way as class jobs, we can maintain this but hopefully SE don't do anymore weirdness. I've checked all other ID's and they look fine.

```
[5] => Lodestone\Entities\Character\Attribute Object
(
    [id:protected] => 27
    [name:protected] => Critical Hit Rate
    [value:protected] => 122
)
```

**Comment by viion** [comment]
All issues from the update should be behind us now and all fixed. `dev` should be in a stable manor.
