### ISSUE TITLE
Random (?) Fatal Errors

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#5]
So, I've noticed periodical errors like these:
```php
[Tue May 02 13:01:33.010936 2017] [:error] PHP Warning:  dom_import_simplexml() expects parameter 1 to be object, boolean given in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/FFTracker/
[Tue May 02 13:01:33.010936 2017] [:error] PHP Notice:  Trying to get property of non-object in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/FFTracker/
[Tue May 02 13:01:33.010936 2017] [:error] PHP Notice:  Trying to get property of non-object in root\\backend\\Lodestone\\Dom\\Document.php on line 197, referer: http://192.168.1.5/FFTracker/
[Tue May 02 13:01:33.010936 2017] [:error] PHP Notice:  Trying to get property of non-object in root\\backend\\Lodestone\\Dom\\Document.php on line 197, referer: http://192.168.1.5/FFTracker/
[Tue May 02 13:01:33.010936 2017] [:error] PHP Warning:  Invalid argument supplied for foreach() in root\\backend\\Lodestone\\Dom\\Document.php on line 197, referer: http://192.168.1.5/FFTracker/
[Tue May 02 13:01:33.010936 2017] [:error] PHP Warning:  dom_import_simplexml() expects parameter 1 to be object, boolean given in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/FFTracker/
[Tue May 02 13:01:33.010936 2017] [:error] PHP Notice:  Trying to get property of non-object in root\\backend\\Lodestone\\Dom\\Document.php on line 94, referer: http://192.168.1.5/FFTracker/
[Tue May 02 13:01:33.010936 2017] [:error] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to DOMXPath::__construct() must be an instance of DOMDocument, null given in root\\backend\\Lodestone\\Dom\\Document.php:156\nStack trace:\n#0 root\\backend\\Lodestone\\Dom\\Document.php(156): DOMXPath->__construct(NULL)\n#1 root\\backend\\Lodestone\\Parser\\Character.php(56): Lodestone\\Dom\\Document->find('.frame__chara__...', 0)\n#2 root\\backend\\Lodestone\\Parser\\Character.php(34): Lodestone\\Parser\\Character->parseProfile()\n#3 root\\backend\\fftracker.php(654): Lodestone\\Parser\\Character->parse()\n#4 root\\backend\\fftracker.php(822): lodestone_grab('8499161', true)\n#5 in root\\backend\\Lodestone\\Dom\\Document.php on line 156, referer: http://192.168.1.5/FFTracker/
```
Thing is, that when I simply retry the call for the company/member that failed like this - it works as expected. Not sure, but most likely this is caused by some connection issue, maybe it gets error 502 for example or something like that. No idea how to simulate this, too.

**Comment by viion** [comment]
Very odd, we can handle this type of thing but it would be good to know the cause. I have noticed similar things, (my tracking has an 80% success rate, so it drops a lot). Most times this happens when lodestone gets a lot of traffic (benchmark just went out). Wondering if that is the cause.

It can also be a cache issue, sometimes lodestone just provides a very bizarre page. 

It would be good to try/catch this and then save the `$html` to see what happened.

**Comment by Simbiat** [comment]
Should we be catching it in dom_import_simplexml() or a level higher?

**Comment by viion** [comment]
I wonder if this happens for companies with 50 people and it's assuming there is a page 2

**Comment by Simbiat** [comment]
dunno. I noticed this mainly on characters. I test changes for FFTracker on my own company. How it goes is that first it gets company data, including all of its pages and then goes to retrieve each character one-by-one (you can try it on webpage like http://simbiat.ru/fftracker/company/fcid/update/ by replacing fcid by your company ID) and sometimes it stops on a random character. I check logs and see a fatal error.

This will make my next update a bit of a pain: I did not include server name in members details initially and new main page of the tracker is dependent on it (like on screenshots here - https://www.facebook.com/simbiatseries/posts/1871757239738757 ), so I will need to update all the members on my side... Not that big of a deal, but probably won't be able to do it in 1 go with such an error. On the other hand this is an opportunity to try and catch this error. Let me know where I should add try/catch for best results and I will add it for the time of manual update.

I hope, that I will commence the update this weekend or the next one at most. I can also add the catch while testing, too.

**Comment by viion** [comment]
Can you reproduce this error when grabbing all members? You could save the output of the html in `HttpRequest`

Just before the return

`file_put_contents(base64_encode($url) .'_code='. $httpCode, $data)`

When the error occures, find the url for the user and base64 it to get the filename and have a look at the html. It might be blank, which means you can check the code=XXX in the filename to see if you got a 503 or something.

**Comment by Simbiat** [comment]
Will see what I can get when I will be testing on weekend

**Comment by Simbiat** [comment]
Well, for some reason sometimes the returned page is just empty. Like even its $response is. Yet cURL treats is as HTTP 200 for some reason. Either way, I created a pull, that would avoid a fatal error in such cases. I am not entirely sure, but perhaps $this->ensureHtml(); is not required now

**Comment by Simbiat** [comment]
Guess, since #11 was closed, this should be closed as well
