### ISSUE TITLE
Wrong hashes (renames in DB required)

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#52]
Thread to collect "undefined index" issues for hashes.
39762c71 can't be found, because on LodeStone it means "Critical Hit Rate", but on http://api.xivdb.com/data/baseparams it's just "Critical Hit"

6fb9b226 - occurred several times, but does not seem to anymore.

e6fa6304 - is taken on "Nald'thal, The Traders", but I do not see any difference in the strings (considering the strtolower).

**Comment by Simbiat** [comment]
6eae1769: Doman Iron Uchigatana. Probably means "Doman Iron Longsword" from DB
08ecaf2d: Hardsilver Uchigatana. No idea
1e953940: Kinna Katana. Probably means "Kinna Blade" from DB

I am starting to wonder, if there is even a point in getting these ids...

**Comment by viion** [comment]
I need true ID's for XIVDB, if they're showing wrong item name on Lodestone then not much we can do really

**Comment by Simbiat** [comment]
hm... urls have hashes - http://eu.finalfantasyxiv.com/lodestone/playguide/db/item/8c88279d3f2/?hq=1
I think it's more reliant to stick to them, rather trying to "convert" to IDs. Besides, if data.php is not updating automatically... Each and every correction on Lodestone may cause warnings/notices.
Also, if it's needed for XVIDB, does not mean it's needed anywhere outside of it. The purpose is to parse, not to create a local copy of XVIDB, right? This can be added into set of options, I think.

**Comment by viion** [comment]
The gamedata does not use those hashes, those hashes are formed by the CDN for cached content, it has no relation to game files which is why they need converting. There were options to remove some XIVDB stuff, however you also cannot get real job ids and names without XIVDB data, or get any ID for minions/mounts.

**Comment by Simbiat** [comment]
why would I need those real IDs?

**Comment by Simbiat** [comment]
So... Cross-service integration. Makes sense. But still, if data.php is not getting updated automatically... Or it does and I am missing something?

**Comment by viion** [comment]
It will be, there is a cache time in it. Everything is still work in progress, you're using a development library.

**Comment by Simbiat** [comment]
I figured that :D

**Comment by Simbiat** [comment]
Issue with Nald'thal, The Traders is fixed with #54

**Comment by Simbiat** [comment]
Closing, since main isue (for me) were excessive notices, which were fixed in a recent pull
