### ISSUE TITLE
parseActiveClass with Paladin

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#56]
Well, the issue is probably not only with Paladin, but I seem to be catching it on him. If a character's active class is Paladin this fails with something like below (lines can be +-1 since copied during debug and I am already too tired for a retest):
```
PHP Notice:  Undefined offset: 1 in root\\backend\\Lodestone\\Entities\\Character\\CharacterProfile.php on line 593
PHP Fatal error:  Uncaught Error: __clone method called on non-object in root\\backend\\Lodestone\\Parser\\Character\\TraitClassJobActive.php:87
Stack trace:
#0 root\\backend\\Lodestone\\Parser\\Character\\Parser.php(61): Lodestone\\Parser\\Character\\Parser->parseActiveClass()
#1 root\\backend\\Lodestone\\Api.php(113): Lodestone\\Parser\\Character\\Parser->parse()
#2 root\\backend\\fftracker.php(1333): Lodestone\\Api->getCharacter('4339591')
#3 root\\backend\\fftracker.php(55): lodestone_grab('4339591', 'character')
#4 root\\index.php(230): ff_id_gateway('4339591', 'character')
#5 {main}
  thrown in root\\backend\\Lodestone\\Parser\\Character\\TraitClassJobActive.php on line 87
```
, because parseActiveClass relies on mainhand which states "Gladiator", which is missing in classes list, because character's page says "Paladin". The proper way seems to be to rely on soul crystals first and then do mainhand if it's missing, but for some reason, but for some reason soulstone is returned empty and for me addGear seems to be adding only mainhand. Or maybe I am misunderstanding here something.

**Comment by viion** [comment]
what character is this? I'll have a look.

There was an issue with Paladin on day 1 but this was fixed and I haven't run into these parse issues yet

**Comment by Simbiat** [comment]
4339591

**Comment by Simbiat** [comment]
as long as levels return job names - I'm fine with it :D
