### ISSUE TITLE
getFreeCompanyMembers ID returning seemingly random member ID?

### ISSUE THREAD

**Issue by darkcloud784** [viion/lodestone-php#58]
I can return the full array with 
```
        $fc_id = '9229001536389032942';
        $freeCompany = $api->getFreeCompanyMembers($fc_id, true);
        print_r($freeCompany);
```

but when I attempt to turn just the ID's for the members, it returns 113 which is not the ID for any of the members. I'm unsure if I'm doing it right at all, any assistance/info would be helpful.

```
        $fc_id = '9229001536389032942';
        $freeCompany = $api->getFreeCompanyMembers($fc_id, true);
         foreach($freeCompany as $member){
        $character = $member['id'];
        print_r($character);
       }
```

**Comment by Simbiat** [comment]
do you get different ones on each run? do you get correct names? do you get same results if not requesting hash? do you get this on any company or just on the one in your sample?

**Comment by viion** [comment]
On this, first:
```php
$freeCompany = $api->getFreeCompanyMembers($fc_id, true);
```

The second parameter should be a number or false. It is "page number", lodestone will list 50 characters per page. If set false lodestone handles it by default (obviously right now thats the first page).

Second: `getFreeCompanyMembers ` does not directly return a list of members, it returns a "page" which contains members and some other info, eg:

```
Array
(
    [page_total] => 1
    [page_current] => 1
    [character_total] => 34
    [members] => Array
        (
            [0] => Array
                (
                    [id] => 6177811
                    [name] => Crystal Rainn
                    [server] => Jenova
                    [rank] => Okami
                    [rankicon] => http://img.finalfantasyxiv.com/lds/h/Z/W5a6yeRyN2eYiaV-AGU7mJKEhs.png
                    [avatar] => http://img2.finalfantasyxiv.com/f/d9c3636b5d7803648bb21c4cad8e3bf0_ce736afe35e2ded4e46c4fd0659aef7efc0_96x96.jpg
                )
....
```

To access members you iterate on `members`, for example:
```php
$id = '9229001536389032942';
$freeCompany = $api->getFreeCompanyMembers($id, 1);
foreach($freeCompany['members'] as $member) {
    print_r($member['id'] . "\n");
}
```

In the near future, `$freeCompany` will be an object and you would access members via: `$freeCompany->members`, but right now use it as an array.

I've put a code test for this in `cli.php` it can be run like so: 
```
php tests/cli.php issue_58
```
