### ISSUE TITLE
New chars from new EU server could not be parsed.

### ISSUE THREAD

**Issue by Ley21** [viion/lodestone-php#59]
I get a error when I try to parse a user from a new server (Omega, Louisoix).

**Comment by viion** [comment]
What error do you get?

I tried on an old parser and it worked, im not sure what would cause it to fail.

eg: https://xivsync.com/character/parse/18365289

**Comment by Simbiat** [comment]
If you're getting character title instead of the server, redownload the library: this bug was fixed recently.

**Comment by Ley21** [comment]
Never mind. Found the issue on my side.
