### ISSUE TITLE
HQ emblums

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#6]
Turns out those crests have higher resolution versions. Noticed by accident. For some reason some of the companies got (as example) http://img2.finalfantasyxiv.com/c/S41_301bb0deaf4ced90e73a7fbed7a85b0a_05_128x128.png instead of http://img2.finalfantasyxiv.com/c/S41_301bb0deaf4ced90e73a7fbed7a85b0a_05_64x64.png which is normally found on the company page. Honestly, no idea, why they even show 64x64, but, could be a good idea to provide 128x128 in the parser result. Maybe, after a check if they exist (random checks did not reveal any inconsistencies, though).

**Comment by viion** [comment]
Ah very nice find.

Would you be able to add this, a simple `str_replace('64x64', '128x128', $icon)` would suffice, I think I do this for the avatar and portrait so you could look there.

**Comment by Simbiat** [comment]
Well, I am adding this in my next FFTracker release, that's for sure, but I thought it would be good to add this in the parser itself. Or did you mean, I can update the code on GitHub? Never tried this before, to  be honest :D And again, I am not sure, we should blindly replace. It may be a good idea to check if image with higher resolution actually exists.
I've checked the avatars and either they do not have higher resolution or it's not an obvious one. Tried 128, 192, 256, 512 - no luck.

**Comment by viion** [comment]
Yes, do a PR :)

- Fork the project.
- Edit the code on your fork, can do it in github or clone it on your machine (push it if you did it locally)
- Then come back to github and it should ask if you want to do a Pull Request.

**Comment by Simbiat** [comment]
I started looking into other images. I see that http://eu.finalfantasyxiv.com/lodestone/freecompany/9234631035923213559/ provides GC images of higher resolution, than seen on http://eu.finalfantasyxiv.com/lodestone/character/6691027/
If you check addresses for Immortal Flames/Ul'dah - they have different names and even "directories". Image name does not look like something obvious like BASE64, so I do not see a way to easily find an image of higher resolution. Furthermore this means, that replacing the names in crest may not be a good idea without a check. And even with it, if they will deprecate resolution in names - it will be just checking the same file.
I will try to fork out a version with a check a bit later

**Comment by viion** [comment]
Replacing the name is fine for now, it will be a solution for a long time (it has been for avatars). They will always depreciate old ones. Avatars used to be: 40, 64 and 96. Now it is just 96.

The ingame icons I may match up to XIVDB rather than using their own since it's unreliable and with XIVDB I can match ID's as well. I do this for gear and I will likely move it to other areas.

**Comment by viion** [comment]
You can do:

```php
$api = new Api();
$data = $api->getCharacter($id);

if ($data['free_company'] && $request->get('addfc')) {
    $data['free_company'] = $api->getFreeCompany($data['free_company']);
}
```
```
"free_company":{  
      "crest":[  
         "http:\/\/img2.finalfantasyxiv.com\/c\/B3f_2b3f1638e91e9a2b521be9b9e3cb43c5_13_64x64.png",
         "http:\/\/img2.finalfantasyxiv.com\/c\/F03_51287a2e97459a52fe56d3534ad2ff9b_00_64x64.png",
         "http:\/\/img2.finalfantasyxiv.com\/c\/S06_c71591351145c0fd6154bc2ce8b33219_03_64x64.png"
      ],
}
```

**Comment by viion** [comment]
I wonder if we could modify the curl request to force Lodestone to serve the Mobile site instead of the main one, this would have a lot of improvements.

**Comment by Simbiat** [comment]
Wow... I did not know mobile version provided higher resolution images. Logic :D Well, since there are higher resolution crests now, closing the issue.
