### ISSUE TITLE
Documentation: Move to `docs/subject.md` or Wiki?

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#60]
The markdown documentation files are getting quite messy and unformatted (specifically the `README`.

I am wondering if we should split up documentation, make it consistent and either place it in a folder `docs/` or use GitHubs Wiki feature?

Thoughts.

**Comment by shentschel** [comment]
There would also be the possibility to provide the data via github pages as website. This would also allow to do some interactive stuff or tracking the most read doc parts.

**Comment by viion** [comment]
Docs have been moved to `docs/` and once in master I will switch the GitHub pages to that directory.

**Comment by viion** [comment]
Documentation is now in the `/docs` folder, I will point the github pages to it once it merges to master.
