### ISSUE TITLE
Subfolder stuff in "Modules"

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#61]
I have moved XIVDB stuff into its own folder:

```
./Modules/
    XIVDB/
       APITrait.php
       XIVDB.php
```

I was thinking of doing the same for the other files like so:

```
./Modules/
    Http/
       HttpRequest.php
       Routes.php
    Logging/
        Benchmark.php
        Logger.php
```

Any thoughts/objections!?

**Comment by shentschel** [comment]
Sounds fine for me :) IMHO: increasing the readability of the structure is always a good point

**Comment by viion** [comment]
Going to do this for the milestone.
