### ISSUE TITLE
Create "dev" branch which all features branch of, master = stable

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#62]
I think for the sake of Packagist and sanity, `master` should be classed as Stable and known to be working (against a timestamp since Lodestone could update and break things out of our control).

`dev` would be what we hot-push to and what all features will branch off.
`dev` would not be considered safe for production and may include `print_r`/`die()`.

Once we feel `dev` is good, it will get merged to `master` and a new release created.

Thoughts/Objections!?

**Comment by shentschel** [comment]
Sounds good. Then we can create feature branches for everything we develop, merge them into dev and when we decide that dev has a stable version, merging it to master. So we can release an old version of master as version and the new version of master as latest. 

My two cents :)

**Comment by viion** [comment]
`dev` branch created based on current master, which I think is in a _decent_ condition... Still need tests

**Comment by viion** [comment]
This is done, `dev` is now the "latest" and contains in development code. The `master` will assume to be stable and be the only branch with releases.
