### ISSUE TITLE
 Uncaught Error: __clone method called on non-object in TraitClassJobActive.php:51

### ISSUE THREAD

**Issue by darkcloud784** [viion/lodestone-php#63]
Ok, so I'm getting the member ID from getFreeCompanyMembers then passing it to getCharacter, then this error is thrown. Later, I want to take the getCharacter information and pull the ranks/icons/etc and display them.

`[:error] [pid 11488] [client 172.68.150.46:18098] PHP Fatal error:  Uncaught Error: __clone method called on non-object in /var/www/html/test/vendor/viion/lodestone-php/src/Lodestone/Parser/Character/TraitClassJobActive.php:51\nStack trace:\n#0 /var/www/html/test/vendor/viion/lodestone-php/src/Lodestone/Parser/Character/Parser.php(61): Lodestone\\Parser\\Character\\Parser->parseActiveClass()\n#1 /var/www/html/test/vendor/viion/lodestone-php/src/Lodestone/Api.php(113): Lodestone\\Parser\\Character\\Parser->parse()\n#2 /var/www/html/test/index.php(20): Lodestone\\Api->getCharacter('6177811')\n#3 {main}\n  thrown in /var/www/html/test/vendor/viion/lodestone-php/src/Lodestone/Parser/Character/TraitClassJobActive.php on line 51`

My code:

`        <?php
        require __DIR__ . '/vendor/autoload.php';
        $api = new Lodestone\Api;
        $fc_id = '9229001536389032942';
        $freeCompany = $api->getFreeCompanyMembers($fc_id, 1);
        foreach($freeCompany['members'] as $members){
        $id = $members['id'];
        $character = $api->getCharacter($id);`

**Comment by viion** [comment]
Have you pulled the latest code changes? I believe this was fixed today.

**Comment by darkcloud784** [comment]
I'll update and try again, I haven't updated today.

**Comment by Simbiat** [comment]
This was fixed, yes and was confirmed in #56 which was closed.

**Comment by darkcloud784** [comment]
Confirmed, this looks to be resolved but when I attempt to get the jobs from getCharacter($id) I get the following:

> PHP Fatal error:  Uncaught Error: Cannot access protected property Lodestone\Entities\Character\CharacterProfile::$classjobs in /var/www/html/fcviewer/cron.php:23
> Stack trace:
> #0 {main}
>   thrown in /var/www/html/fcviewer/cron.php on line 23

```
My code:
$freeCompany = $api->getFreeCompanyMembers($fc_id, 1);
foreach($freeCompany['members'] as $member) {
        $id = $member['id'];
        $character = $api->getCharacter($id);
        $rank = "<img src='" . $member["rankicon"] . "' title='" . $member["rank"] . "'/>";
        $ClassJobs = $character->classjobs;
```
Again, I'm just learning php so I apologize if I'm just not doing this as intended by the API.

**Comment by viion** [comment]
No apologies needed!

I think there is meant to be a `getClassJobs()` but it doesn't seem to exist, I've added it on dev.

You might be able to use `$character->toArray();` to get everything as an array.

**Comment by darkcloud784** [comment]
@viion Unfortunately it doesnt look like I can use toArray(); as I get an error as seen below. I'll try using getClassJobs() once that is in the master. Thanks for the help and I appreciate the understanding!

> PHP Fatal error:  Uncaught Error: __clone method called on non-object in /var/www/html/test/vendor/viion/lodestone-php/src/Lodestone/Parser/Character/TraitClassJobActive.php:53\nStack trace:\n#0 /var/www/html/test/vendor/viion/lodestone-php/src/Lodestone/Parser/Character/Parser.php(61): Lodestone\\Parser\\Character\\Parser->parseActiveClass()\n#1 /var/www/html/test/vendor/viion/lodestone-php/src/Lodestone/Api.php(113): Lodestone\\Parser\\Character\\Parser->parse()\n#2 /var/www/html/test/index.php(20): Lodestone\\Api->getCharacter('6177811')\n#3 {main}\n  thrown in /var/www/html/test/vendor/viion/lodestone-php/src/Lodestone/Parser/Character/TraitClassJobActive.php on line 53

**Comment by Simbiat** [comment]
I confirm, that I am getting the same error on latest release

**Comment by Simbiat** [comment]
Fixed in #64

**Comment by viion** [comment]
Added a test in the `cli.php` file for this issue: `php tests/cli.php issue_63`

code:
```php
$fc_id = '9229001536389032942';
$freeCompany = $api->getFreeCompanyMembers($fc_id, 1);
foreach($freeCompany['members'] as $members) {
    $id = $members['id'];
    $character = $api->getCharacter($id);
    print_r("Hello: ". $character->getName() . "\n");
}
die;
```

### Note

The code logic of looping through all characters will parse lodestone in realtime, this will be very slow for users. It would be worth looking into using a cronjob to handle this and cache the data, your users then load the cached data.

**Comment by Simbiat** [comment]
Seems like there is another issue on miners (and possibly others):

```
PHP Fatal error:  Uncaught Error: Call to a member function isset() on boolean in root/backend/Lodestone/Parser/Character/TraitClassJobActive.php:44
Stack trace:
#0 root/backend/Lodestone/Parser/Character/Parser.php(61): Lodestone\Parser\Character\Parser->parseActiveClass()
#1 root/backend/Lodestone/Api.php(113): Lodestone\Parser\Character\Parser->parse()
#2 root/backend/fftracker.php(1334): Lodestone\Api->getCharacter('3693861')
#3 root/backend/fftracker.php(528): lodestone_grab('3693861', 'character')
#4 root/backend/fftracker.php(83): freecompany_update(Array)
#5 root/index.php(232): ff_id_gateway('923463103592321...', 'freecompany')
#6 {main}
  thrown in root/backend/Lodestone/Parser/Character/TraitClassJobActive.php on line 44
```

**Comment by viion** [comment]
@Simbiat are you on `dev` branch?

This is fixed: https://github.com/viion/lodestone-php/commit/3644c7159db995255437a0e67c04296621b23490

**Comment by Simbiat** [comment]
no. that was found on master. did not check dev.

**Comment by darkcloud784** [comment]
@viion  Looks like the getClassJobs() function you added in returns nothing but protected items in the array.

`Array ( [19] => Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 19 [classId:protected] => 1 [name:protected] => Paladin [level:protected] => 61 [expLevel:protected] => 4671876 [expLevelTogo:protected] => 201124 [expLevelMax:protected] => 4873000 [expTotal:protected] => 38612676 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 61401124 ) [21] => Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 21 [classId:protected] => 3 [name:protected] => Warrior [level:protected] => 60 [expLevel:protected] => 14 [expLevelTogo:protected] => 4469986 [expLevelMax:protected] => 4470000 [expTotal:protected] => 29470814 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 70542986 ) [32] => Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 32 [classId:protected] => 32 [name:protected] => Dark Knight [level:protected] => 60 [expLevel:protected] => 0 [expLevelTogo:protected] => 4470000 [expLevelMax:protected] => 4470000 [expTotal:protected] => 29470800 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 70543000 ) [20] => Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 20 [classId:protected] => 2 [name:protected] => Monk [level:protected] => 60 [expLevel:protected] => 0 [expLevelTogo:protected] => 4470000 [expLevelMax:protected] => 4470000 [expTotal:protected] => 29470800 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 70543000 ) [22] => Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 22 [classId:protected] => 4 [name:protected] => Dragoon [level:protected] => 60 [expLevel:protected] => 0 [expLevelTogo:protected] => 4470000 [expLevelMax:protected] => 4470000 [expTotal:protected] => 29470800 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 70543000 ) [30] => Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 30 [classId:protected] => 29 [name:protected] => Ninja [level:protected] => 60 [expLevel:protected] => 0 [expLevelTogo:protected] => 4470000 [expLevelMax:protected] => 4470000 [expTotal:protected] => 29470800 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 70543000 ) [34] => Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 34 [classId:protected] => 34 [name:protected] => Samurai [level:protected] => 50 [expLevel:protected] => 96000 [expLevelTogo:protected] => 768000 [expLevelMax:protected] => 864000 [expTotal:protected] => 7830000 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 92183800 ) [24] => Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 24 [classId:protected] => 6 [name:protected] => White Mage [level:protected] => 65 [expLevel:protected] => 1766410 [expLevelTogo:protected] => 5228590 [expLevelMax:protected] => 6995000 [expTotal:protected] => 58069210 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 41944590 ) [28] => Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 28 [classId:protected] => 26 [name:protected] => Scholar [level:protected] => 60 [expLevel:protected] => 0 [expLevelTogo:protected] => 4470000 [expLevelMax:protected] => 4470000 [expTotal:protected] => 29470800 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 70543000 ) [33] => Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 33 [classId:protected] => 33 [name:protected] => Astrologian [level:protected] =>...etc`

**Comment by shentschel** [comment]
when you do `$character->getClassJobs()` you have to use the array in the following way:

```php

$classJobs  = $character->getClassJobs();
foreach($classJobs AS $classJob) {
  $classJob->getLevel()
  ... do something with the rest ...
}
```

for all the available getter-methods, have a look into the [ClassJob class](https://github.com/viion/lodestone-php/blob/dev/src/Lodestone/Entities/Character/ClassJob.php) :)

**Comment by darkcloud784** [comment]
@shentschel Even if I do use it in this manner, it still comes back protected.

```
     require __DIR__ . '/vendor/autoload.php';
        $api = new Lodestone\Api;
        $fc_id = '9229001536389032942';
        $freeCompany = $api->getFreeCompanyMembers($fc_id, 1);
        foreach ($freeCompany['members'] as $member) {
            $id = $member['id'];
            $character = $api->getCharacter($id);
            $ClassJobs = $character->getClassJobs();
            foreach ($ClassJobs as $classJob) {
            $classJob->getLevel();
                }
            print_r($classJob);
```


`Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 18 [classId:protected] => 18 [name:protected] => Fisher [level:protected] => 60 [expLevel:protected] => 0 [expLevelTogo:protected] => 4470000 [expLevelMax:protected] => 4470000 [expTotal:protected] => 29470800 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 70543000 ) Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 18 [classId:protected] => 18 [name:protected] => Fisher [level:protected] => 12 [expLevel:protected] => 9194 [expLevelTogo:protected] => 10406 [expLevelMax:protected] => 19600 [expTotal:protected] => 70074 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 99943726 ) Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 18 [classId:protected] => 18 [name:protected] => Fisher [level:protected] => 44 [expLevel:protected] => 201582 [expLevelTogo:protected] => 189218 [expLevelMax:protected] => 390800 [expTotal:protected] => 5204482 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 94809318 ) Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 18 [classId:protected] => 18 [name:protected] => Fisher [level:protected] => 60 [expLevel:protected] => 83700 [expLevelTogo:protected] => 4386300 [expLevelMax:protected] => 4470000 [expTotal:protected] => 29554500 [expTotalMax:protected] => 100013800 [expTotalTogo:protected] => 70459300 ) Lodestone\Entities\Character\ClassJob Object ( [jobId:protected] => 18 [classId:protected] => 18 [name:protected] => Fisher [level:protected] => 0 [expLevel:protected] => 0 [expLevelTogo:protected] => 0 [expLevelMax:protected] => 0 [expTotal:protected] => 0 [expTotalMax:protected] =>`

**Comment by viion** [comment]
```
$classJob->getLevel();
print_r($classJob);
```

You have not assigned level to anything, and you're printing the object. Have a read of: http://php.net/manual/en/language.oop5.visibility.php

The `variables` are protected
The `methods` are public

You're meant to do something like:

```php
echo "Character ls level" . $classJob->getLevel();
```

You don't use the object, you use the return method :)

Some useful stuff for you to read up on:

- http://php.net/manual/en/language.oop5.php
- http://php.net/manual/en/language.types.object.php

**Comment by viion** [comment]
```
$classJob->getLevel();
print_r($classJob);
```

You have not assigned level to anything, and you're printing the object. Have a read of: http://php.net/manual/en/language.oop5.visibility.php

The `variables` are protected
The `methods` are public

You're meant to do something like:

```php
echo "Character ls level" . $classJob->getLevel();
```

You don't use the object, you use the return method :)

Some useful stuff for you to read up on:

- http://php.net/manual/en/language.oop5.php
- http://php.net/manual/en/language.types.object.php

**Comment by shentschel** [comment]
$classJob is a class of type ClassJob. Maybe the following example is a little better:

```php 
$classJobs = $character->getClassJobs();
foreach($classJobs AS $classJob) {
  $level = $classJob->getLevel();
  print_r($level);
}
```

Or if you want the classJob as an array:

```php 
$classJobs = $character->getClassJobs();
foreach($classJobs AS $classJob) {
  $array = $classJob->toArray();
  print_r($array);
}
```

I hope that it clarifies the use-case (and I hope there is no typo - had to write it with my mobile phone) x)

**Comment by darkcloud784** [comment]
@viion @shentschel  Thanks for the help, I think I understand. I'm just trying to grab each FC members job level and then store them into my sql database while learning at the same time XD. I think its easiest for me to use arrays for this, but wasn't sure how to return a non-protected item within the array so I can match it with their corresponding character id.

**Comment by viion** [comment]
Going to close this, if another issue similar pops up could you make a new issue and include any character ID's :)
