### ISSUE TITLE
Handling of : SMN, ARC and SCH

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#65]
New issue due to a topic shift from #51 

**General Issue**: Arcanist is the only class that goes into both Summoner and Scholar. This causes problems when trying to track the "class" for levelling purposes as the `id` would be the same for them both.

The current solution is to leave as-is, the `classjobs` array contains both Summoner and Scholar classes and their data will end up being the same but that isn't an issue.

The ActiveClass will also display the correct one depending on which soul stone the charactr has equipped.

The main issue is with developers (like myself) using it and needing something consistent. For example I track character leveling, I cannot use `job` because it would create inconsistent timelines, eg: Level 40-45 on Scholar, 45-50 on Summoner... It would logically skip levels when you actually level the class "Arcanist" and all data is under that umbrella.

I can handle things my side, so to keep things consistent with what lodestone shows, I think its current implementation of containing both SMN and SCH is fine.

Any other thoughts or problems, fire away, I'll leave this issue up for about a week

**Comment by shentschel** [comment]
IMHO even SE covers both classes in the same list. So it would also be consistent with lodestone.

**Comment by viion** [comment]
this is true, being consistent with Lodestone is true.I am thinking beyond what lodestone does. Lodestone just shows classes and your exp/level, it doesn't show any stats, or any totals.

On XIVDB I have a lot of stats, so I have to track Arcanist, I cannot track SMN or SCH otherwise the timelines on XIVDB would become incorrect and split up. It also causes issues with the "Total EXP Tracking" because you effectively get double each time, making it look like you need twice as much exp..

The reason it's a concern is because if you're just using the API to display some basic info for your FC then fair enough, if you're building a tool to show more than lodestone then you'll run into these issues. If you have a tool just outputting roles then whats the point really.. Does what lodestone already does.

**Comment by shentschel** [comment]
I think on this point we have a different view on the project. Because my view was from a perspective described by you in the readme.

> The goal is to provide an extremely fast and lightweight library, it is built with the purpose of parsing as many characters as possible, key being: Low memory, and micro-timed parsing methods.

I can understand your opinion of calculating total exp and doing stuff beyond parsing but I think we should focus on parsing the lodestone to provide an initial set of data to work with. In my opinion we should split of all non-parsing related stuff into another project which is built ontop of the parsing library. That would also us to build a light-weight library and it would allow the end user to decide if he needs the extra stuff oder only parsing data from lodestone to show stuff.

I'm sorry for not being able to have a better way with words but I hope you can also understand my point of view :)

**Comment by viion** [comment]
Could do... Remove all the XIVDB stuff and any re-mapping and then the data is "whatever lodestone has, nothing changed"

**Comment by shentschel** [comment]
Bad day? X) I'm open for discussion and feedback but in the end it is your decision as the project lead. All I can do is giving you my opinion and some code. 

Another opinion For the smn, arc, sch I have is:

Is there a way to distinguish between classes and jobs? If yes, maybe we can add an class-attribute to the jobs and use that as a starting point for calculations and other stuff. What's are your thoughts about that @viion?


Von meinem iPhone gesendet

**Comment by viion** [comment]
It is possible to distinguish, and it's also possible to hardcode ID's to enable this because SE are not going to remove or change existing classes, only add new ones (easy maintenance).

Right now, the output would be:
```
[28] => Lodestone\Entities\Character\ClassJob Object
    (
        [jobId:protected] => 28
        [classId:protected] => 26
        [name:protected] => Scholar
        [level:protected] => 0
        [expLevel:protected] => 0
        [expLevelTogo:protected] => 0
        [expLevelMax:protected] => 0
        [expTotal:protected] => 0
        [expTotalMax:protected] => 100013800
        [expTotalTogo:protected] => 100013800
    )
```

As you can see, both `jobId` and `classId` exist. If the role is only a class, eg: *Conjurer* then its `jobId` is the same as `classId` but not sure if that is a worry.

In the example above you can see `jobId = 28` which is the ID for Scholar, but it has `classId = 26` which is the ID for Arcanist.

This means any tools using classes for EXP calculations/predictions can use the classId to record growth (what I do on XIVDB). It also saves in the array against `jobId` now. This is kind of new, previously all Scholar and Summoner weapons would say "Arcanist Arms", however Stormblood added `Scholar's Arm` which almost makes it look like a real class. Which means if you have a scholar book equip the "ActiveClass" can find it because it uses `jobId`, if you have a Summoner Book your arm will be "Arcanist" (I haven't tested if this fails.)

It may be worth removing id's all together, any "exp stats" and saving the role against the "name" and handling things from there.

**Comment by viion** [comment]
Trusting lodesotne: http://eu.finalfantasyxiv.com/lodestone/character/?q=&worldname=&classjob=26&race_tribe=&gcid=&gcid=&gcid=&blog_lang=ja&blog_lang=en&blog_lang=de&blog_lang=fr&order=5

Characters labeled "Level 70 Arcanist", yet are all botany/miner .... Luckily our API handles this correct as we use the "Weapon". `/hurray` ...

**Comment by viion** [comment]
This character fails "ActiveClass`: http://eu.finalfantasyxiv.com/lodestone/character/1557944/

SE is listing Summoner instead of Arcanist, but they do not have the Summoner Soul Stone equipped so it can't find the ActiveClass because the job list is `jobId` but the ActiveClass is `classId`.

(Wouldn't have this issue if we combined Sch/Smn to Arcanist XD)

**Comment by shentschel** [comment]
So to summarize:

* it is possible to distinguish the ids
* An Archanist will be listed as summoner w/o a soul stone
* SE is not able to show consistent data in the lodestone...

Some questions to think about:
* What are the pros and cons about using the name instead of the id's?
* can we use a fallback strategy with our current solution? e.g. first looking for job and if not found looking for class afterwards
* what are the pros and cons of only using the class id?

Seems to be a pretty complex topic (even without the bugs in the lodestone)

**Comment by viion** [comment]
Lodestone does not provide ID's and so that is fetched from the game files (XIVDB). It is only in there because I think a more ID centric API is better, I wanted everything to be ID at the end (FC, GC, Title, Server, Guardian... etc). However I can see how this can be annoying. I was thinking about it more in storage (I add about 5,000 rows to mysql every minute, so ID's are a lot more optimal than strings).

---

### Using the `name` instead of `id`

**Pro** We don't rely on the game files or XIVDB data, it can be stripped. Reduces additional querying and time spent there.

**Con** You have to manage this, it's not friendly to have the id as `White Mage`, what if they suddenly change it to `WhiteMage` or White mage`, so you have to then `strtolower`, remove spaces, trim it down as much as possible to it's bare minimum.

You also have the same issue as class/job, do you store `lancer` or `dragoon`..

---

### Fallback strategy

Probably, to avoid parsing additional "ActiveClass" and because lodestone does not say what is the Active class (the job/class name is an image with a CDN hash), we rely on the weapon. Weapons will always say the class, eg: `Marauder's Arm` so we have to factor that, look for Marauder, if it don't exist we have to find `Warrior`, it's a lot of additional checking and something we'd need to manage.

---

### Using just `classId`

**Pro** This would strip everything down and make it easier to know what class the character is on because weapons use Class names (excluding Scholar)

**Con** You only have 1 entry for "Arcanist" and it is up to the developer to visually include 2 in their work and use the same data for both.

**Comment by shentschel** [comment]
Hmm then I would stick with the classId stuff and document the edge-case with scholar. TBH: I like the id more than a changing name. I mean when they can do something like WhiteMage they can also du something like whm or White Mag.. what do you think?

**Comment by viion** [comment]
We can revert all XIVDB stuff and keep ID as converting `name` to `id` is simple and the ids will be fixed. Never change...

We could add scholar as an edge case, so the array contains just classes with "job" names optional, if the developer wants to use job name they can. We store everything against `classId` and scholar gets tacked on like `[26-2] => [...]` possibly... Don't know really...

I would rather just have classes and then in your application you can list it twice.

**Comment by shentschel** [comment]
Let us try it :) If we don't like it we can change it in another version x)

**Comment by viion** [comment]
This won't be part of the coming milestone. I will do it after that. For a master release I am going to implement an "arrayIndexExists" type validation check which will be added to the `ActiveClass` as that is the main bit that fails.

Then make a new branch that begins ripping out XIVDB

**Comment by viion** [comment]
this has been fully solved. `ActiveClass` no longer fails or cares about `SoulCrystal` and roles can be obtained by both classname or jobname. Both Arc+Sch an Arc+Smn will be listed.

https://github.com/viion/lodestone-php/pull/71
