### ISSUE TITLE
Handling of Malformed characters

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#66]
You'd think Lodestone would be perfect and not mess up, however..

### http://eu.finalfantasyxiv.com/lodestone/character/1044326/

- Has Conjurer and Thaumaturge level 1
- Has Bard gear on at least level 50, however class display says Archer isn't even unlocked...
- No number next to "Level" on Active Class display

Parse error:

```
PHP Fatal error:  Uncaught Error: __clone method called on non-object in /Users/joshfreeman/Web/Misc/lodestone-php/src/Lodestone/Parser/Character/TraitClassJobActive.php:53
Stack trace:
#0 /Users/joshfreeman/Web/Misc/lodestone-php/src/Lodestone/Parser/Character/Parser.php(61): Lodestone\Parser\Character\Parser->parseActiveClass()
#1 /Users/joshfreeman/Web/Misc/lodestone-php/src/Lodestone/Api.php(113): Lodestone\Parser\Character\Parser->parse()
#2 /Users/joshfreeman/Web/Misc/lodestone-php/tests/cli.php(32): Lodestone\Api->getCharacter('1044326')
#3 {main}
  thrown in /Users/joshfreeman/Web/Misc/lodestone-php/src/Lodestone/Parser/Character/TraitClassJobActive.php on line 53

Fatal error: Uncaught Error: __clone method called on non-object in /Users/joshfreeman/Web/Misc/lodestone-php/src/Lodestone/Parser/Character/TraitClassJobActive.php on line 53

Error: __clone method called on non-object in /Users/joshfreeman/Web/Misc/lodestone-php/src/Lodestone/Parser/Character/TraitClassJobActive.php on line 53

Call Stack:
    0.0003     369608   1. {main}() /Users/joshfreeman/Web/Misc/lodestone-php/tests/cli.php:0
    0.0103    1918640   2. Lodestone\Api->getCharacter() /Users/joshfreeman/Web/Misc/lodestone-php/tests/cli.php:32
    1.2151    2463392   3. Lodestone\Parser\Character\Parser->parse() /Users/joshfreeman/Web/Misc/lodestone-php/src/Lodestone/Api.php:113
    1.3534    3101504   4. Lodestone\Parser\Character\Parser->parseActiveClass() /Users/joshfreeman/Web/Misc/lodestone-php/src/Lodestone/Parser/Character/Parser.php:61
```

**Issue**

The weapon category comes back as "Bard", however due to the bugged class list, "Bard" does not exist and so it cannot find the class/job when it tries to grab it from the list and clone it...

Not sure where to put the error, maybe directly on setting the role in `TraitClassJobActive`

**Comment by shentschel** [comment]
A non issue related question/thought about the "Merge to master" tag.

IMHO I would expect that tag only in the case that an issue is ready to be merged to master.

-----

A issue related opinion:

For that special case maybe I would create an empty bard class with the least minimal information possible (e.g. level 0 or 1 and 0 exp) and maybe a simple note somewhere that this information was generated due to a bug on lodestone

**Comment by viion** [comment]
If we create empty classes we're going to over-inflate the array. This is one of my problems with how SCH + SMN does.

If you add up the total amount of EXP to get 1-70 for ALL Classes, you will get an incorrect value because SCH + SMN is added twice, but you wouldn't ever need to get EXP For the other as 1 is both... If we add all blank classes then the whole array would just look like "36 classes!".

I was thinking of doing a validation rule for `ArrayKeyExists` which would trigger on this kind of issue. I need to find other possible malformed characters

**Comment by viion** [comment]
Closing as a fix for this specific issue has been pushed, other issues will have to be handled on a case-by-case basis as we could parse a 1000 characters and not find another issue!
