### ISSUE TITLE
Does getLodestoneMaintenance return a boolean?

### ISSUE THREAD

**Issue by darkcloud784** [viion/lodestone-php#67]
Again, forgive me if I'm just being stupid (and its late), but I'm attempting to check if lodestone is under maintenance before proceeding with the rest of my functions. I was hoping to make a simple if/else statement to check if it is currently operational. Is this possible, I could not find any resource in the docs that indicate what value this call returns.

**Comment by shentschel** [comment]
When I remember right (no code at hand) there will be an exception if the lodestone is in maintenance. You can try-catch it :)

**Comment by viion** [comment]
As @shentschel mentioned, you would use exceptions for this, eg:

```
try {
  $character = $api->getCharacter(<id>)
} catch (HttpMaintenanceValidationException $hmvex) {
  ... code to handle lodestone down for maintenance ...
} catch (HttpNotFoundValidationException $hnfvex) {
  ... code for page not found / deleted ...
} catch (ValidationException $vex) {
  ... code for some other issue (eg data corrupt) ...
}
```

**Comment by darkcloud784** [comment]
So whats the point of getLodestoneMaintenance?

**Comment by viion** [comment]
That tells you when Maintenance is, not if the site is currently under maintenance. There are two very different things.

That function, returns this: http://eu.finalfantasyxiv.com/lodestone/news/category/2/

**Comment by darkcloud784** [comment]
@viion  Thanks for clearing that up, that makes a lot more sense.
