### ISSUE TITLE
Parsing achievements not returning all achievements

### ISSUE THREAD

**Issue by Colbydude** [viion/lodestone-php#68]
Was looking to parse all achievements for my character for an old tool that I made. However, I'm not sure if what's returned is limited to a special list of achievements or it may actually be a bug.

Let me know if I need to provide any additional information for debugging.

Brief code sample of what I'm parsing:
```php
<?php

$api = new \Lodestone\Api();

$character = (Object) $api->searchCharacter('Enyl Noves', 'Leviathan');

$achievements = (Object) $api->getCharacterAchievements($search->results[0]['id']);

return $achievements;
```

**Comment by shentschel** [comment]
How do you fetch the list of achievements?

**Comment by Colbydude** [comment]
Just simply running the following:

```php
<?php

$api = new \Lodestone\Api();

$character = (Object) $api->searchCharacter('Enyl Noves', 'Leviathan');

$achievements = (Object) $api->getCharacterAchievements($search->results[0]['id']);

return $achievements;
```

Then dumping to json.

**Comment by shentschel** [comment]
Only to be sure: How many entries contains the list of achievements? (I guess 50)

**Comment by Colbydude** [comment]
list has 315 entries
list_possible also has 315 entries
points has possible at 3035 with obtained being 1010

My character _actually_ has 4305 points out of the possible 13420.

**Comment by shentschel** [comment]
Ok now I know what went wrong :)

If you provide no "kind" of achievement it always does this:

```php
public function getCharacterAchievements($id, $kind = 1) {
  ... internal logic ...
}
```
but achievements with kind-id = 1 are only battle achievements... 

There are 2 ways to fix this:

1. We can change the behavior of the search (only use `kind` when a number is provided)
2. You can iterate over all kinds of achievements and calculate the sum yourself (and we need to update the docs to show how many kinds are available)

@viion what do you think about this?

**Comment by Colbydude** [comment]
Ah! I wasn't aware there was even a second parameter you could pass in. Thank you. :)

You may want to update the README to reflect that. ;)

**Comment by viion** [comment]
@shentschel Its added to the `docs` branch: https://github.com/viion/lodestone-php/blob/docs/docs/ApiCharacters.md

The reason it doesn't do them all in 1 go is because it will cause up to 13 pages being parsed and may be unexpectedly slow.

**Comment by shentschel** [comment]
👍  :)
