### ISSUE TITLE
Move tests to PHP Unit

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#7]
Currently tests is a simple automated method call script that determines it's pass state on if the response was empty or not, with the exception of those with `@softpass` enabled.

The current script is:
- https://github.com/viion/lodestone-php/blob/master/tests/run.php

Proposing to move to this to PHP and test each method for specific data returned, for example if SE change how character names are shown, the API will likely still return data.

**Comment by shentschel** [comment]
I can also have a look into it :)

**Comment by viion** [comment]
Done a bit more on this, fixed up Validation errors and made a new Branch `tests` from `dev`. I have started character tests. https://github.com/viion/lodestone-php/tree/tests/tests/Lodestone/Entities

Because I want test lots of characters to ensure non were a fluke I started moving valid character tests to a `commonValidCharacter` method. I will probably do the same for `NoFreeCompany`, `NoGrandCompany` and `NotFound`.

It is assumed most data should exist for all characters, company being the only exceptions.

More tests will need adding to the common method such as checking gear (mainhand) exists and has some valid data.

**Comment by viion** [comment]
going to remove from milestone as a lot needs doing, will add a checklist to the OP.

**Comment by viion** [comment]
This is done. Tests will be done in `phpunit` for all future tests. `run.php` exists as a quick way to check your system works with the API.

**Comment by shentschel** [comment]
good job :D I'm sorry for being so inactive currently x)
