### ISSUE TITLE
PHP Fatal error:  Uncaught Lodestone\\Validator\\Exceptions\\ValidationException: HTML cannot be empty.

### ISSUE THREAD

**Issue by Dyr-Fenrir** [viion/lodestone-php#74]
Greetings,

I am receiving the following in my web server logs:

PHP Fatal error:  Uncaught Lodestone\\Validator\\Exceptions\\ValidationException: HTML cannot be empty. in <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Validator\\Exceptions\\ValidationException.php:55\nStack trace:\n#0 <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Validator\\BaseValidator.php(90): Lodestone\\Validator\\Exceptions\\ValidationException::emptyValidation(Object(Lodestone\\Validator\\BaseValidator))\n#1 <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Parser\\Html\\ParserHelper.php(101): Lodestone\\Validator\\BaseValidator->isNotEmpty()\n#2 <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Parser\\Html\\ParserHelper.php(82): Lodestone\\Parser\\Html\\ParserHelper->ensureHtml()\n#3 <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Parser\\FreeCompany\\Search.php(37): Lodestone\\Parser\\Html\\ParserHelper->initialize()\n#4 <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Api.php(94): Lodestone\\P in <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Validator\\Exceptions\\ValidationException.php on line 55

The same code was working some months ago (I had to stop development on my website for a while).

My code is:

```
<?php
require __DIR__ . '/vendor/autoload.php';
$api = new \Lodestone\Api;
$fc = $api->searchFreeCompany('<redacted>','<redacted>');
$chars = $api->getFreeCompanyMembers($fc['id']);

//echo '<pre>'; print_r($fc); echo '</pre>';

foreach($fc['results'] as $fc) {
    $fc = (Object)$fc;
	print_r($fc->id);echo '<br>' ;
	print_r($fc->name);echo '<br>' ;
	echo '<br>' ;
}

$chars = $api->getFreeCompanyMembers($fc->id);

foreach($chars['members'] as $chars) {
    $chars = (Object)$chars;
	print_r($chars->id); echo '<br>' ;
	print_r($chars->name);echo '<br>' ;
	print_r($chars->rank); echo '<br>' ;
	echo '<br>' ;
}

$chars = $api->getFreeCompanyMembers($fc->id);

foreach($chars['members'] as $chars) {
    $chars = (Object)$chars;
	$char_info = $api->getCharacter($chars->id);
	echo '<pre>'; print_r($char_info); echo '</pre>';
}

?>
```

I updated:

PHP to the latest release
composer to the latest release
lodestone-php to the latest release
symphony/css to the latest release

Can you help me with this error please?

Thank you for your time and help.

**Comment by viion** [comment]
Hello!

Your code does not make sense at the start.

```php
$fc = $api->searchFreeCompany('<redacted>','<redacted>');
$chars = $api->getFreeCompanyMembers($fc['id']);
```

The variable `$fc` in this instance would be a search result, did you mean to use `getFreeCompany` ? (if you know the id). You're mis-using a lot of the objects by trying to access things directly `$chars->name`, you can't do this, and `chars['members']`, it's not an array.

You might need to read up a bit on object-oriented programming :)

Here is some working code:

```php
<?php

// composer auto loader
require __DIR__.'/../vendor/autoload.php';

$api = new \Lodestone\Api;

$results = $api->searchFreeCompany('Equilibrium','Phoenix');

/** @var \Lodestone\Entities\FreeCompany\FreeCompany $fc */
foreach($results->getFreeCompanies() as $fc) {
    $chars = $api->getFreeCompanyMembers($fc->getId());

    foreach($chars->getCharacters() as $chars) {
        echo "
            {$chars->getId()} <br> 
            {$chars->getName()} <br> 
            {$chars->getRank()} <br><br>
        ";
    }
}
```

**Comment by Dyr-Fenrir** [comment]
Greetings,

Thanks for the fast reply, it's greatly appreciated!

I do understand that I am not an expert at coding, I still have a lot to learn.

I did try the code you provided and I still get the same error message, is it possible that I might be missing a requirement or a configuration in one of the configuration files for either Apache or PHP?

`PHP Fatal error:  Uncaught Lodestone\\Validator\\Exceptions\\ValidationException: HTML cannot be empty. in <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Validator\\Exceptions\\ValidationException.php:55\nStack trace:\n#0 <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Validator\\BaseValidator.php(90): Lodestone\\Validator\\Exceptions\\ValidationException::emptyValidation(Object(Lodestone\\Validator\\BaseValidator))\n#1 <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Parser\\Html\\ParserHelper.php(101): Lodestone\\Validator\\BaseValidator->isNotEmpty()\n#2 <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Parser\\Html\\ParserHelper.php(82): Lodestone\\Parser\\Html\\ParserHelper->ensureHtml()\n#3 <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Parser\\FreeCompany\\Search.php(37): Lodestone\\Parser\\Html\\ParserHelper->initialize()\n#4 <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Api.php(94): Lodestone\\P in <redacted>\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Validator\\Exceptions\\ValidationException.php on line 55`

To answer your question:

> The variable $fc in this instance would be a search result, did you mean to use getFreeCompany ?

I did a search first to not have to find the id of the Free Company, I was not sure if those were subject to change, so if I find it every time, I will always retrieve the good one.

Thank you again for your time and help.

**Comment by viion** [comment]
What version of PHP are you using? This requires 7.1 so make sure you're on that.

From the looks of it you're getting no html response, which can also happen if `curl` is not enabled or is failing.

**Comment by Dyr-Fenrir** [comment]
Greetings,

I am using:

- Apache 2.4.29
- PHP 7.1.11

I also made sure CURL was enabled (in PHP.ini) through phpinfo and I tested it with:

```
// reinitialize curl resource
$ch = curl_init();// set url
curl_setopt($ch, CURLOPT_URL, “domain.com”);

//return the as a string
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

// echo output string
$output = curl_exec($ch);

echo $output;

        // close curl resource to free up system resources
curl_close($ch);
```

Which was working fine.

I am still looking if I can find something else, do you have any other suggestions please? It would be greatly appreciated.

Thank you again for your time and help.

**Comment by viion** [comment]
Parsing lodestone is a bit different than parsing some pages, it has browser checks. You could try that but it looks like it should be all working.

Does your FC that you're searching for have any random symbols or letters? I am wondering if there is a problem if a FC is named "!I XX I!" or something... it might be failing url

Add these to the top of your script:

```
define('BENCHMARK_ENABLED', true);
define('LOGGER_ENABLED', true);
define('LOGGER_ENABLE_PRINT_TIME', true);
```

It should output a bunch of logging and show you the url it parses which might give you some clue

**Comment by Dyr-Fenrir** [comment]
Greetings,

The only special characters are spaces in the FC name, it's called Tempest of Might and it's on Balmung.

All my recent attempts were done with the code you provided above (thanks a lot again for that).

Here is the output I got by adding the lines you suggested:

`[2017-11-09 17:40:25-4577][Lodestone\Modules\Http\HttpRequest][40] GET: http://na.finalfantasyxiv.com/lodestone/freecompany?q=Equilibrium&worldname=Phoenix [2017-11-09 17:40:26-3311][Lodestone\Modules\Http\HttpRequest][56] RESPONSE: 301 `

I tried the code with Internet Explorer, Chrome and Firefox (if it can help in any way).

Thank you.

**Comment by Dyr-Fenrir** [comment]
Greetings,

I am receiving different errors with the update:

`PHP Fatal error:  Uncaught Lodestone\\Validator\\Exceptions\\ValidationException: Requested page is not available in D:\\My Web Sites\\Tempest of Might\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Validator\\HttpRequestValidator.php:77\nStack trace:\n#0 D:\\My Web Sites\\Tempest of Might\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Modules\\Http\\HttpRequest.php(63): Lodestone\\Validator\\HttpRequestValidator->isNotHttpError()\n#1 D:\\My Web Sites\\Tempest of Might\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Parser\\Html\\ParserHelper.php(51): Lodestone\\Modules\\Http\\HttpRequest->get('https://na.fina...')\n#2 D:\\My Web Sites\\Tempest of Might\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Api.php(94): Lodestone\\Parser\\Html\\ParserHelper->url('https://na.fina...')\n#3 D:\\My Web Sites\\Tempest of Might\\lodestone.php(45): Lodestone\\Api->searchFreeCompany('Equilibrium', 'Phoenix')\n#4 {main}\n  thrown in D:\\My Web Sites\\Tempest of Might\\vendor\\viion\\lodestone-php\\src\\Lodestone\\Validator\\HttpRequestValidator.php on line 77`

And:

`[2017-11-09 18:49:44-4864][Lodestone\Modules\Http\HttpRequest][40] GET: https://na.finalfantasyxiv.com/lodestone/freecompany?q=Equilibrium&worldname=Phoenix [2017-11-09 18:49:44-9041][Lodestone\Modules\Http\HttpRequest][56] RESPONSE: 0`

Thank you again for your time and help.

**Comment by viion** [comment]
I've disabled peer verification, but might not help. Response 0 is really strange ...

**Comment by Dyr-Fenrir** [comment]
Greetings,

I was able to find this:

> SSL certificate problem: unable to get local issuer certificateCurl error: SSL certificate problem: unable to get local issuer certificateReturn code is 0 SSL certificate problem: unable to get local issuer certificate

Using the following code (from the link you suggested):

```
<?php

$html_brand = "https://na.finalfantasyxiv.com/lodestone/freecompany?q=Equilibrium&worldname=Phoenix";
$ch = curl_init();

$options = array(
    CURLOPT_URL            => $html_brand,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_HEADER         => true,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_ENCODING       => "",
    CURLOPT_AUTOREFERER    => true,
    CURLOPT_CONNECTTIMEOUT => 120,
    CURLOPT_TIMEOUT        => 120,
    CURLOPT_MAXREDIRS      => 10,
);
curl_setopt_array( $ch, $options );
$response = curl_exec($ch); 
print curl_error($ch);
$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
if(curl_errno($ch)){   
    echo 'Curl error: ' . curl_error($ch);
}

if ( $httpCode != 200 ){
    echo "Return code is {$httpCode} \n"
        .curl_error($ch);
} else {
    echo "<pre>".htmlspecialchars($response)."</pre>";
}

curl_close($ch);

?>
```

I'll fix this and try again.

Thanks again, I am almost there I hope.

**Comment by Dyr-Fenrir** [comment]
Greetings.

I had to download the cURL certificate from: [https://curl.haxx.se/ca/cacert.pem](https://curl.haxx.se/ca/cacert.pem)

And set this parameter in the PHP.ini to the path of the certificate:

```
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
curl.cainfo=
```

It's now working.

I would also like to apologize as the error was on my end, it was a configuration issue and not an issue with actual code.

Thank you again for all your time and help, you pointed me in the right direction and it was greatly appreciated.
