### ISSUE TITLE
Add validation checking for core content

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#8]
Currently if data is empty or not as expected it will still return a array and attempt to handle the data. The core pieces to valid would be:

- Character data
- Linkshell data
- Free Company data

Other than just checking it's empty or not, some could have further checks, eg:

- 2 names exist for character name?

**Comment by shentschel** [comment]
_Just for Mindsharing_

How about an extendable validation class which allows to check for basic stuff like empty objects.
Then it would be possible to create a class for every data type (e.g.: character data). So we can gain a maintainable code.

I could try to create a pull request if that idea is ok :)

**Comment by viion** [comment]
Sounds good, I was originally just going to check if empty etc, but really needs to be a bit more extendable (checking 2 names, checking server name is correct, checking for ints, and where things expect an id, etc)

**Comment by viion** [comment]
Closing this as work has begun, discussion here: https://github.com/viion/lodestone-php/issues/21
