### ISSUE TITLE
Patch 4.2

### ISSUE THREAD

**Issue by viion** [viion/lodestone-php#84]
Lodestone has updated, something with Attributes has broken

**Comment by viion** [comment]
Resistances and elementals have been removed

**Comment by viion** [comment]
Removed Elements and Resistances: https://github.com/viion/lodestone-php/commit/8dc65bd7e47b59d73e53e3120554a30a316a9433

**Comment by viion** [comment]
New achievement category: https://eu.finalfantasyxiv.com/lodestone/character/730968/achievement/kind/3/

I recommend we add some kind of static class so that we could do `AchievementCategory::LIST` to get all the valid ids

**Comment by viion** [comment]
A class for achievement categories have been created: https://github.com/viion/lodestone-php/blob/master/src/Lodestone/Modules/Game/AchievementsCategory.php

No other issues from 4.2, closing

**Comment by NHDriver4** [comment]
Sorry to post in a closed thread but was this resolved? I'm getting an error on character refresh with attributes.

**Comment by viion** [comment]
Hello

Yes it was, however I don't think a release was made. I've just done one now so if you do composer update it should pick up `1.9` and that should fix your issues

**Comment by NHDriver4** [comment]
Thanks. @viion. I had just updated my composer to pickup the latest dev. I'll switch back to release. Thanks for your hard work on this!
