### ISSUE TITLE
PvP Team corrupts FreeCompany ID

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#89]
If a character has PvP team, but no FreeCompany - PvP team's ID is returned. Example - ID 14944156. Dunno what will be the case with both PvP team and FreeCompany.

And, BTW, it may be a good idea to add PvP teams as well (= I was, actually planning to do this, but now even more reason to.

**Comment by viion** [comment]
I didn't know PVP Teams existed, is that new? It looks very easy to fix, since it has it's own label and even its own classname `character__pvpteam__name`.

I think adding PVP Teams is a good idea and looks very easy to parse

**Comment by Simbiat** [comment]
yes, it's relatively new, maybe a month now, not more. I still have a few days of vacation and will try to implement them based on linkshell-parser (seems more suited than FC one) and fix this "bug" here, too.

**Comment by viion** [comment]
Yeah the Linkshell format seems perfect. If you don't get around to it I can always jump on tomorrow. I am actually working on character stuff for XIVDB so I don't mind.

**Comment by Simbiat** [comment]
I will to be implementing the tracker for them, too, so will work on it, no worries. If all will go according to plan, it will be done tomorrow.

**Comment by Simbiat** [comment]
Can be closed now with merger of #90
